#!/bin/zsh

# We need:
#   + torrent?
#   + sound
#     - pulseaudio master volume
#     - muted?
#     - headphones?
#   + disks, (used/total)
#     - ~
#     - /
#   + CPU (all cores)
#     - load
#     - frequency
#    + RAM
#      - used/total
#      - load
#   + network
#      - IP
#      - DHCP?
#      - ESSID (if wifi)
#      - rate quality (if wifi)
#   + power
#      - battery remaining if present
#   + date

# unicode symbols
local black=`echo -ne "\u2B1B"`
local white=`echo -ne "\u2B1C"`
local power_sign=`echo -ne "\u26A1"`

# system constants
local home_disk=/dev/sda2
local root_disk=/dev/sda2

user_mod() {
  echo '{ "full_text": "'$USER' ", "color": "#B16286" },'
}

amixer_mod() {
  line=`amixer get Master | grep 'Front Left: Playback' | tr -s ' ' | tr -d '[]'`
  volume=`echo $line | cut -d' ' -f6`
  muted=`echo $line | cut -d' ' -f7`

  if [[ $muted == "on" ]]
  then
    echo '{ "full_text": " \u266A '$volume' ", "color": "#B8BB26" },'
  else
    echo '{ "full_text": " \u266A '$volume' ", "color": "#7C6F64" },'
  fi
}

disk_mod() {
  test -e $2 || return;

  line=`df -h --output=used,size $2 | tail -n1 | tr -s ' '`
  used=`echo $line | cut -d' ' -f2`
  total=`echo $line | cut -d' ' -f3`

  echo '{ "full_text": " '$1 $used/$total' ", "color": "'$3'" },'
}

root_disk_mod() {
  line=`df -h --output=used,size $root_disk | tail -n1 | tr -s ' '`
  used=`echo $line | cut -d' ' -f2`
  total=`echo $line | cut -d' ' -f3`

  echo '{ "full_text": " \u2302 '$used/$total' ", "color": "#83A598" },'
}


ram_mod() {
  ram_line=`free -m | head -n3 | tail -n2`
  total=`echo $ram_line | head -n1 | tr -s ' ' | cut -d' ' -f2`
  used=`echo $ram_line | tail -n1 | tr -s ' ' | cut -d' ' -f3`
  frac=$((total / 5))

  if [[ $used -lt $frac ]]
  then
    echo '{ "full_text": " '$white$white$white$white $used/$total' ", "color": "#83A598" },'
  elif [[ $used -lt $((frac * 2)) ]]
  then
    echo '{ "full_text": " '$black$white$white$white $used/$total' ", "color": "#B8BB26" },'
  elif [[ $used -lt $((frac * 3)) ]]
  then
    echo '{ "full_text": " '$black$black$white$white $used/$total' ", "color": "#FABD2F" },'
  elif [[ $used -lt $((frac * 4)) ]]
  then
    echo '{ "full_text": " '$black$black$black$white $used/$total' ", "color": "#FE8019" },'
  else
    echo '{ "full_text": " '$black$black$black$black $used/$total' ", "color": "#FB4934" },'
  fi
}

local_ip_mod() {
  local_ip=`ip -o addr show | grep -v ": lo" | grep "inet " | head -n1 | tr -s ' ' | cut -d' ' -f4`

  echo '{ "full_text": " \u23DA '$local_ip' ", "color": "#689D6A" },'
}

power_mod() {
  adp=`cat /sys/class/power_supply/ADP1/online 2> /dev/null` || return
  battery_present=`cat /sys/class/power_supply/BAT1/present 2> /dev/null` || return
  capacity=`cat /sys/class/power_supply/BAT1/capacity 2> /dev/null` || return

  if [ $adp == "0" ]
  then
    battery_mod $capacity
  elif [ $battery_present == "1" ]
  then
    status=`cat /sys/class/power_supply/BAT1/status`
    echo '{ "full_text": " '$power_sign $status $capacity'% ", "color": "#B8BB26" },'
  fi
}

battery_mod() {
  capacity=$1

  if [[ capacity -lt 8 ]]
  then
    color='#CC241D'
    level=$white$white$white$white$white
  elif [[ capacity -lt 20 ]]
  then
    color='#FB4934'
    level=$black$white$white$white$white
  elif [[ capacity -lt 40 ]]
  then
    color='#D65D0E'
    level=$black$black$white$white$white
  elif [[ capacity -lt 60 ]]
  then
    color='#FABD2F'
    level=$black$black$black$white$white
  elif [[ capacity -lt 80 ]]
  then
    color='#8EC07C'
    level=$black$black$black$black$white
  else
    color='#B8BB26'
    level=$black$black$black$black$black
  fi

  echo '{ "full_text": " '$power_sign $level $capacity'% ", "color": "'$color'" },'
}

date_mod() {
  d=`date +'%a %b %d'`
  echo '{ "full_text": " '$d' ", "color": "#83A598" },'

}

time_mod () {
  d=`date +'%H:%M:%S'`
  echo '{ "full_text": " \u231A '$d'", "color": "#D3869B" }'
}

echo '{ "version": 1 }'
echo '['

while true; do
  a=(
    `echo '['
    user_mod
    amixer_mod
    disk_mod "\u2302" $home_disk "#FB4934"
    disk_mod "/" $root_disk "#83A598"
    ram_mod
    local_ip_mod
    power_mod
    battery_mod 100
    date_mod
    time_mod
    echo '],'`
    )

  echo $a
  sleep 1
done
